"""initial_schema

Revision ID: 8ce29f5d5fac
Revises: 
Create Date: 2026-06-10 05:05:06.722833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce29f5d5fac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('air_quality_readings',
    sa.Column('reading_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aqi', sa.Integer(), nullable=False),
    sa.Column('pm25', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pm10', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('co', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('no2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('so2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('o3', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_index('ix_air_quality_location_timestamp', 'air_quality_readings', ['location_id', 'timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_value', sa.Integer(), nullable=False),
    sa.Column('actual_aqi', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('aqi_predictions',
    sa.Column('prediction_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('prediction_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_aqi', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aqi_predictions')
    op.drop_table('alerts')
    op.drop_index('ix_air_quality_location_timestamp', table_name='air_quality_readings')
    op.drop_table('air_quality_readings')
    op.drop_table('locations')
    # ### end Alembic commands ###
